# Add 'repo' label to any root file changes
repo:
  - any: ['./*', '!./*.xcodeproj']

# Add 'test' label to any change files within the test directories
test:
  - any: ['SudoguTests/**/*', 'SudoguUITests/**/*']

# Add 'main' label to any change to target files within the target dir EXCEPT for the docs sub-folder
main:
  - any: ['Sudogu/**/*', '!Sudogu/PreviewContent/*']

frontend:
  - any: ['Sudogu/Content Views/**/*.swift', 'Sudogu/*.swift']
    
backend:
  - any: ['Sudogu/Models/**/*.swift', 'Sudogu/API Extensions/**/*.swift']

# Add 'assests' label to any change to *.swift files within the 'Sudogu/Assets'
assests:
  - any: ['Sudogu/Assets/**/*]
