name: Swift CI
on:
#  pull_request:
#    branches: [ master, release ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - { project: 'Sudogu.xcodeproj', scheme: 'Sudogu', destination: 'platform=iOS Simulator,name=iPhone 11 Pro,OS=latest' }
          - { project: 'Sudogu.xcodeproj', scheme: 'Sudogu', destination: 'platform=iOS Simulator,name=iPad Pro (12.9-inch),OS=latest' }
          - { project: 'Sudogu.xcodeproj', scheme: 'Sudogu', destination: 'platform=macOS,OS=latest' }
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Show the currently detailed version of Xcode for CLI
      run: xcode-select -p
    - name: Show Build Settings
      run: xcodebuild -project ${{ matrix.config['project'] }} -scheme ${{ matrix.config['scheme'] }} -showBuildSettings
    - name: Show Build SDK
      run: xcodebuild -project ${{ matrix.config['project'] }} -scheme ${{ matrix.config['scheme'] }} -showsdks
    - name: Show Available Destinations
      run: xcodebuild -project ${{ matrix.config['project'] }} -scheme ${{ matrix.config['scheme'] }} -showdestinations
    - name: Build for Deployment
      run: xcodebuild -project ${{ matrix.config['project'] }} -scheme ${{ matrix.config['scheme'] }} -destination '${{ matrix.config['destination'] }}' -configuration Release build CODE_SIGNING_ALLOWED=NO
#    - name: Build and Test
#      run: xcodebuild clean test -project Sudogu.xcodeproj -scheme ${{ matrix.config['scheme'] }} -destination '${{ matrix.config['destination'] }}' -showBuildTimingSummary
